Repository sosy-lab/sv-benchmarks, pull requests merged in 2020-12, with the labels that each got.

#1252 Initializing local variables to fix undefined behaviors
  c/aws-c-common/aws_priority_queue_s_sift_down_harness.i
Labels: C, issue with benchmark

#1254 seq-mthreaded: fix termination lablel at several benchmraks
  c/seq-mthreaded/pals_floodmax.3.3.ufo.UNBOUNDED.pals.yml
  c/seq-mthreaded/pals_floodmax.3_overflow.ufo.UNBOUNDED.pals.yml
  c/seq-mthreaded/pals_lcr.3_overflow.ufo.UNBOUNDED.pals.yml
  c/seq-mthreaded/pals_lcr.4_overflow.ufo.UNBOUNDED.pals.yml
  c/seq-mthreaded/pals_lcr.5_overflow.ufo.UNBOUNDED.pals.yml
  c/seq-mthreaded/pals_opt-floodmax.3.2.ufo.UNBOUNDED.pals.yml
  c/seq-mthreaded/pals_opt-floodmax.3.3.ufo.UNBOUNDED.pals.yml
  c/seq-mthreaded/pals_opt-floodmax.3_overflow.ufo.UNBOUNDED.pals.yml
Labels: C, issue with benchmark

#1255 Added BSD 2-clause license to licenses, REUSE spec to each Java file.
  .reuse/dep5
  LICENSES/BSD-2-Clause.txt
  java/rtems-lock-model/lock-00-01-10/Main.java
  java/rtems-lock-model/lock-00-01-10/base/Condition.java
  java/rtems-lock-model/lock-00-01-10/base/Lock.java
  java/rtems-lock-model/lock-00-01-10/base/PrioLock.java
  java/rtems-lock-model/lock-00-01-10/harness/Environment.java
  java/rtems-lock-model/lock-00-01-10/harness/TestThread.java
  java/rtems-lock-model/lock-00-01-10/rtems/Mutex.java
  java/rtems-lock-model/lock-00-01-10/rtems/OrderList.java
  java/rtems-lock-model/lock-00-01-10/rtems/RTEMSThread.java
  java/rtems-lock-model/lock-00-01-10/rtems/WaitQueue.java
Labels: Java

#1256 Avoid uninitialized variable usage in c/bitvector/s3_clnt_?.BV.c.cil-2a.c
  c/bitvector/s3_clnt_1.BV.c.cil-2a.c
  c/bitvector/s3_clnt_2.BV.c.cil-2a.c
  c/bitvector/s3_clnt_3.BV.c.cil-2a.c
Labels: C, for test generation, issue with benchmark

#1253 Properly initialize local variables in c/aws-c-common/mem*.i
  c/aws-c-common/memcpy_using_uint64_harness.i
  c/aws-c-common/memset_override_0_harness.i
  c/aws-c-common/memset_using_uint64_harness.i
Labels: C, issue with benchmark

#1258 termination-recursive-malloc/chunk3.c: remove double free
  c/termination-recursive-malloc/chunk3.c
  c/termination-recursive-malloc/chunk3.i
Labels: C, issue with benchmark

#1260 Fix termination verdicts in seq-mthreaded
  c/seq-mthreaded/pals_floodmax.4.2.ufo.UNBOUNDED.pals.yml
  c/seq-mthreaded/pals_floodmax.4.3.ufo.UNBOUNDED.pals.yml
  c/seq-mthreaded/pals_floodmax.4_overflow.ufo.UNBOUNDED.pals.yml
  c/seq-mthreaded/pals_floodmax.5.2.ufo.UNBOUNDED.pals.yml
  c/seq-mthreaded/pals_floodmax.5_overflow.ufo.UNBOUNDED.pals.yml
  c/seq-mthreaded/pals_lcr.6_overflow.ufo.UNBOUNDED.pals.yml
  c/seq-mthreaded/pals_lcr.7_overflow.ufo.UNBOUNDED.pals.yml
  c/seq-mthreaded/pals_lcr.8_overflow.ufo.UNBOUNDED.pals.yml
  c/seq-mthreaded/pals_opt-floodmax.4.2.ufo.UNBOUNDED.pals.yml
  c/seq-mthreaded/pals_opt-floodmax.4.3.ufo.UNBOUNDED.pals.yml
  c/seq-mthreaded/pals_opt-floodmax.4_overflow.ufo.UNBOUNDED.pals.yml
  c/seq-mthreaded/pals_opt-floodmax.5.2.ufo.UNBOUNDED.pals.yml
  c/seq-mthreaded/pals_opt-floodmax.5_overflow.ufo.UNBOUNDED.pals.yml
Labels: C, issue with benchmark

#1265 Remove c/ntdrivers/floppy2.i.cil.yml
  c/ntdrivers/floppy2.i.cil.yml
Labels: C, issue with benchmark

#1274 ldv-linux-3.0/module_get_put-drivers-gpu-drm-i915-i915.ko.cil.out: allocate memory
  c/ldv-linux-3.0/module_get_put-drivers-gpu-drm-i915-i915.ko.cil.out.c
  c/ldv-linux-3.0/module_get_put-drivers-gpu-drm-i915-i915.ko.cil.out.i
Labels: C, issue with benchmark

#1278 Fix possible undefined behavior and intent of loops/linear_search and loops/linear_sea.ch
  c/loops/linear_sea.ch.c
  c/loops/linear_search.c
Labels: C, issue with benchmark

#1271 Add missing initialisation in ntdrivers/parport.i.cil-2
  c/ntdrivers/parport.i.cil-2.c
Labels: C, issue with benchmark

#1279 Fix Problems with Benchmark Set
  c/ldv-regression/rule57_ebda_blast.yml
  c/ldv-regression/test28-1.c
  c/loops/s3.i
  c/openssl/s3_clnt.blast.01.i.cil-1.c
  c/openssl/s3_clnt.blast.01.i.cil-2.c
  c/openssl/s3_clnt.blast.02.i.cil-1.c
  c/openssl/s3_clnt.blast.02.i.cil-2.c
  c/openssl/s3_clnt.blast.03.i.cil-1.c
  c/openssl/s3_clnt.blast.03.i.cil-2.c
  c/openssl/s3_clnt.blast.04.i.cil-1.c
  c/openssl/s3_clnt.blast.04.i.cil-2.c
  c/openssl/s3_srvr.blast.01.i.cil-1.c
  c/openssl/s3_srvr.blast.01.i.cil-2.c
  c/openssl/s3_srvr.blast.02.i.cil-1.c
  c/openssl/s3_srvr.blast.02.i.cil-2.c
  c/openssl/s3_srvr.blast.03.i.cil.c
  c/openssl/s3_srvr.blast.04.i.cil.c
  c/openssl/s3_srvr.blast.06.i.cil-1.c
  c/openssl/s3_srvr.blast.06.i.cil-2.c
  c/openssl/s3_srvr.blast.07.i.cil-1.c
  c/openssl/s3_srvr.blast.07.i.cil-2.c
  c/openssl/s3_srvr.blast.08.i.cil-1.c
  c/openssl/s3_srvr.blast.08.i.cil-2.c
  c/openssl/s3_srvr.blast.09.i.cil-1.c
  c/openssl/s3_srvr.blast.09.i.cil-2.c
  c/openssl/s3_srvr.blast.10.i.cil-1.c
  c/openssl/s3_srvr.blast.10.i.cil-2.c
  c/openssl/s3_srvr.blast.11.i.cil-1.c
  c/openssl/s3_srvr.blast.11.i.cil-2.c
  c/openssl/s3_srvr.blast.12.i.cil-1.c
  c/openssl/s3_srvr.blast.12.i.cil-2.c
  c/openssl/s3_srvr.blast.13.i.cil-1.c
  c/openssl/s3_srvr.blast.13.i.cil-2.c
  c/openssl/s3_srvr.blast.14.i.cil-1.c
  c/openssl/s3_srvr.blast.14.i.cil-2.c
  c/openssl/s3_srvr.blast.15.i.cil-1.c
  c/openssl/s3_srvr.blast.15.i.cil-2.c
  c/openssl/s3_srvr.blast.16.i.cil-1.c
  c/openssl/s3_srvr.blast.16.i.cil-2.c
Labels: C, for test generation, issue with benchmark

#1267 ntdrivers/diskperf.i.cil-1: remove duplicate initialisation
  c/ntdrivers/diskperf.i.cil-1.c
Labels: C, issue with benchmark
