Repository sosy-lab/sv-benchmarks, pull requests merged in 2020-09, with the labels that each got.

#1114 Fixup preprocessing of pthread-driver-races after d2bfcfc1599
  c/pthread-driver-races/char_generic_nvram_nvram_llseek_nvram_unlocked_ioctl.i
  c/pthread-driver-races/char_generic_nvram_nvram_llseek_read_nvram.i
  c/pthread-driver-races/char_generic_nvram_nvram_llseek_write_nvram.i
  c/pthread-driver-races/char_generic_nvram_nvram_unlocked_ioctl_write_nvram.i
  c/pthread-driver-races/char_generic_nvram_read_nvram_nvram_unlocked_ioctl.i
  c/pthread-driver-races/char_generic_nvram_read_nvram_write_nvram.i
  c/pthread-driver-races/char_pc8736x_gpio_pc8736x_gpio_change_pc8736x_gpio_configure.i
  c/pthread-driver-races/char_pc8736x_gpio_pc8736x_gpio_change_pc8736x_gpio_current.i
  c/pthread-driver-races/char_pc8736x_gpio_pc8736x_gpio_change_pc8736x_gpio_get.i
  c/pthread-driver-races/char_pc8736x_gpio_pc8736x_gpio_change_pc8736x_gpio_set.i
  c/pthread-driver-races/char_pc8736x_gpio_pc8736x_gpio_configure_pc8736x_gpio_current.i
  c/pthread-driver-races/char_pc8736x_gpio_pc8736x_gpio_configure_pc8736x_gpio_get.i
  c/pthread-driver-races/char_pc8736x_gpio_pc8736x_gpio_configure_pc8736x_gpio_set.i
  c/pthread-driver-races/char_pc8736x_gpio_pc8736x_gpio_current_pc8736x_gpio_get.i
  c/pthread-driver-races/char_pc8736x_gpio_pc8736x_gpio_current_pc8736x_gpio_set.i
  c/pthread-driver-races/char_pc8736x_gpio_pc8736x_gpio_get_pc8736x_gpio_set.i
  c/pthread-driver-races/char_pc8736x_gpio_pc8736x_gpio_open_pc8736x_gpio_change.i
  c/pthread-driver-races/char_pc8736x_gpio_pc8736x_gpio_open_pc8736x_gpio_configure.i
  c/pthread-driver-races/char_pc8736x_gpio_pc8736x_gpio_open_pc8736x_gpio_current.i
  c/pthread-driver-races/char_pc8736x_gpio_pc8736x_gpio_open_pc8736x_gpio_get.i
  c/pthread-driver-races/char_pc8736x_gpio_pc8736x_gpio_open_pc8736x_gpio_set.i
  c/pthread-driver-races/model/undef_funcs_generic_nvram.h
  c/pthread-driver-races/model/undef_funcs_pc8736x_gpio.h
Labels: issue with benchmark

#1117 Create an empty Makefile to please CI
  c/ldv-challenges/model/Makefile
  c/ldv-commit-tester/model/Makefile
  c/ldv-consumption/model/Makefile
  c/ldv-linux-3.0/model/Makefile
  c/ldv-linux-3.12-rc1/model/Makefile
  c/ldv-linux-3.14-races/model/Makefile
  c/ldv-linux-3.14/model/Makefile
  c/ldv-linux-3.16-rc1/model/Makefile
  c/ldv-linux-3.4-simple/model/Makefile
  c/ldv-linux-3.7.3/model/Makefile
  c/ldv-linux-4.0-rc1-mav/model/Makefile
  c/ldv-linux-4.2-rc1/model/Makefile
  c/ldv-sets/model/Makefile
  c/ldv-validator-v0.6/model/Makefile
  c/ldv-validator-v0.8/model/Makefile
  c/pthread-driver-races/model/Makefile
Labels: CI

#1113 Document the new version of the SV-COMP task-definition format
  README.md
Labels: build system and metadata, documentation

#1132 Add .set and .cfg file for new (demo) category on data races
  c/NoDataRace-Main.cfg
  c/NoDataRace-Main.set
Labels: C, category definitions, data-race

#1139 Add a build script for the Docker image
  .gitlab-ci.yml
  .travis.yml
  java/.Dockerfile
  java/check-compile.sh
  java/compile.xml
Labels: CI
