Repository sosy-lab/sv-benchmarks, pull requests merged in 2020-11, with the labels that each got.

#1211 Seeded an off-by-one bug
  c/aws-c-common/aws_array_eq_c_str_harness-1.i
  c/aws-c-common/aws_array_eq_c_str_harness-1.yml
Labels: C, new benchmarks

#1216 Restore original benchmark semantics
  c/ldv-races/race-2_2-container_of.c
  c/ldv-races/race-2_2-container_of.i
  c/ldv-races/race-2_5-container_of.c
  c/ldv-races/race-2_5-container_of.i
Labels: C, data-race, issue with benchmark

#1218 Solved data races
  c/ldv-races/race-2_3-container_of.c
  c/ldv-races/race-2_3-container_of.i
  c/pthread-ext/18_read_write_lock.c
  c/pthread-ext/18_read_write_lock.i
Labels: C, data-race

#1221 Passing size of 0 to malloc leads to assertion violation
  c/aws-c-common/aws_string_eq_byte_buf_harness.i
  c/aws-c-common/aws_string_new_from_array_harness.i
Labels: C, issue with benchmark

#1226 Fix confusing mismatch between yml file and benchmark directory
  java/juliet-java/CWE369_Divide_by_Zero__float_connect_tcp_divide_81a_bad.yml
  java/juliet-java/CWE369_Divide_by_Zero__float_connect_tcp_divide_81a_bad_version2.yml
  java/juliet-java/CWE369_Divide_by_Zero__float_connect_tcp_divide_81a_good.yml
  java/juliet-java/CWE369_Divide_by_Zero__float_console_readLine_divide_54_bad.yml
  java/juliet-java/CWE369_Divide_by_Zero__float_console_readLine_divide_54_bad_version2.yml
  java/juliet-java/CWE369_Divide_by_Zero__float_console_readLine_divide_54_good.yml
Labels: Java, issue with benchmark

#1222 Yet another data race
  c/ldv-races/race-2_4-container_of.c
  c/ldv-races/race-2_4-container_of.i
Labels: C, data-race, issue with benchmark

#1228 Added ldv_ prefix to strlen and strerror function definitions
  c/ldv-commit-tester/m0_drivers-media-radio-si4713-i2c-ko--111_1a--064368f-1.c
  c/ldv-commit-tester/m0_drivers-media-radio-si4713-i2c-ko--111_1a--064368f-1.i
  c/ldv-commit-tester/m0_drivers-media-radio-si4713-i2c-ko--111_1a--064368f.c
  c/ldv-commit-tester/m0_drivers-media-radio-si4713-i2c-ko--111_1a--064368f.i
  c/ldv-commit-tester/m0_drivers-scsi-gdth-ko--111_1a--5934df9-1.c
  c/ldv-commit-tester/m0_drivers-scsi-gdth-ko--111_1a--5934df9-1.i
  c/ldv-commit-tester/m0_sound-oss-opl3-ko--111_1a--42f9f8d-1.c
  c/ldv-commit-tester/m0_sound-oss-opl3-ko--111_1a--42f9f8d-1.i
  c/ldv-commit-tester/m0_sound-oss-opl3-ko--111_1a--42f9f8d.c
  c/ldv-commit-tester/m0_sound-oss-opl3-ko--111_1a--42f9f8d.i
  c/ldv-validator-v0.6/linux-stable-064368f-1-111_1a-drivers--media--radio--si4713-i2c.ko-entry_point.cil.out.c
  c/ldv-validator-v0.6/linux-stable-064368f-1-111_1a-drivers--media--radio--si4713-i2c.ko-entry_point.cil.out.i
  c/ldv-validator-v0.6/linux-stable-42f9f8d-1-111_1a-sound--oss--opl3.ko-entry_point.cil.out.c
  c/ldv-validator-v0.6/linux-stable-42f9f8d-1-111_1a-sound--oss--opl3.ko-entry_point.cil.out.i
  c/ldv-validator-v0.6/linux-stable-5934df9-1-111_1a-drivers--scsi--gdth.ko-entry_point.cil.out.c
  c/ldv-validator-v0.6/linux-stable-5934df9-1-111_1a-drivers--scsi--gdth.ko-entry_point.cil.out.i
  c/ldv-validator-v0.8/linux-stable-064368f-1-111_1a-drivers--media--radio--si4713-i2c.ko-entry_point_ldv-val-v0.8.cil.out.c
  c/ldv-validator-v0.8/linux-stable-064368f-1-111_1a-drivers--media--radio--si4713-i2c.ko-entry_point_ldv-val-v0.8.cil.out.i
  c/ldv-validator-v0.8/linux-stable-42f9f8d-1-111_1a-sound--oss--opl3.ko-entry_point_ldv-val-v0.8.cil.out.c
  c/ldv-validator-v0.8/linux-stable-42f9f8d-1-111_1a-sound--oss--opl3.ko-entry_point_ldv-val-v0.8.cil.out.i
  c/ldv-validator-v0.8/linux-stable-5934df9-1-111_1a-drivers--scsi--gdth.ko-entry_point_ldv-val-v0.8.cil.out.c
  c/ldv-validator-v0.8/linux-stable-5934df9-1-111_1a-drivers--scsi--gdth.ko-entry_point_ldv-val-v0.8.cil.out.i
  c/ldv-validator-v0.8/linux-stable-8817633-1-144_2a-drivers--staging--media--easycap--easycap.ko-entry_point_ldv-val-v0.8.cil.out.c
  c/ldv-validator-v0.8/linux-stable-8817633-1-144_2a-drivers--staging--media--easycap--easycap.ko-entry_point_ldv-val-v0.8.cil.out.i
Labels: C, issue with benchmark

#1235 Fix labelling of uthash tasks with property violation memtrack
  c/uthash-2.0.2/uthash_BER_test1-1.yml
  c/uthash-2.0.2/uthash_BER_test10-1.yml
  c/uthash-2.0.2/uthash_BER_test2-1.yml
  c/uthash-2.0.2/uthash_BER_test3-1.yml
  c/uthash-2.0.2/uthash_BER_test4-1.yml
  c/uthash-2.0.2/uthash_BER_test5-1.yml
  c/uthash-2.0.2/uthash_BER_test8-1.yml
  c/uthash-2.0.2/uthash_BER_test9-1.yml
  c/uthash-2.0.2/uthash_FNV_test1-1.yml
  c/uthash-2.0.2/uthash_FNV_test10-1.yml
  c/uthash-2.0.2/uthash_FNV_test2-1.yml
  c/uthash-2.0.2/uthash_FNV_test3-1.yml
  c/uthash-2.0.2/uthash_FNV_test4-1.yml
  c/uthash-2.0.2/uthash_FNV_test5-1.yml
  c/uthash-2.0.2/uthash_FNV_test8-1.yml
  c/uthash-2.0.2/uthash_FNV_test9-1.yml
  c/uthash-2.0.2/uthash_JEN_test1-1.yml
  c/uthash-2.0.2/uthash_JEN_test10-1.yml
  c/uthash-2.0.2/uthash_JEN_test2-1.yml
  c/uthash-2.0.2/uthash_JEN_test3-1.yml
  c/uthash-2.0.2/uthash_JEN_test4-1.yml
  c/uthash-2.0.2/uthash_JEN_test5-1.yml
  c/uthash-2.0.2/uthash_JEN_test8-1.yml
  c/uthash-2.0.2/uthash_JEN_test9-1.yml
  c/uthash-2.0.2/uthash_OAT_test1-1.yml
  c/uthash-2.0.2/uthash_OAT_test10-1.yml
  c/uthash-2.0.2/uthash_OAT_test2-1.yml
  c/uthash-2.0.2/uthash_OAT_test3-1.yml
  c/uthash-2.0.2/uthash_OAT_test4-1.yml
  c/uthash-2.0.2/uthash_OAT_test5-1.yml
  c/uthash-2.0.2/uthash_OAT_test8-1.yml
  c/uthash-2.0.2/uthash_OAT_test9-1.yml
  c/uthash-2.0.2/uthash_SAX_test1-1.yml
  c/uthash-2.0.2/uthash_SAX_test10-1.yml
  c/uthash-2.0.2/uthash_SAX_test2-1.yml
  c/uthash-2.0.2/uthash_SAX_test3-1.yml
  c/uthash-2.0.2/uthash_SAX_test4-1.yml
  c/uthash-2.0.2/uthash_SAX_test5-1.yml
  c/uthash-2.0.2/uthash_SAX_test8-1.yml
  c/uthash-2.0.2/uthash_SAX_test9-1.yml
  c/uthash-2.0.2/uthash_SFH_test1-1.yml
  c/uthash-2.0.2/uthash_SFH_test10-1.yml
  c/uthash-2.0.2/uthash_SFH_test2-1.yml
  c/uthash-2.0.2/uthash_SFH_test3-1.yml
  c/uthash-2.0.2/uthash_SFH_test4-1.yml
  c/uthash-2.0.2/uthash_SFH_test5-1.yml
  c/uthash-2.0.2/uthash_SFH_test8-1.yml
  c/uthash-2.0.2/uthash_SFH_test9-1.yml
Labels: C, issue with benchmark

#1236 change labelling for some Juliet tasks.
  c/Juliet_Test/CWE401_Memory_Leak---s01---CWE401_Memory_Leak__int64_t_calloc_45_bad.yml
  c/Juliet_Test/CWE401_Memory_Leak---s01---CWE401_Memory_Leak__int64_t_calloc_68_bad.yml
  c/Juliet_Test/CWE401_Memory_Leak---s01---CWE401_Memory_Leak__int64_t_malloc_45_bad.yml
  c/Juliet_Test/CWE401_Memory_Leak---s01---CWE401_Memory_Leak__int64_t_malloc_68_bad.yml
  c/Juliet_Test/CWE401_Memory_Leak---s01---CWE401_Memory_Leak__int64_t_realloc_45_bad.yml
  c/Juliet_Test/CWE401_Memory_Leak---s01---CWE401_Memory_Leak__int64_t_realloc_68_bad.yml
  c/Juliet_Test/CWE401_Memory_Leak---s01---CWE401_Memory_Leak__int_calloc_45_bad.yml
  c/Juliet_Test/CWE401_Memory_Leak---s01---CWE401_Memory_Leak__int_calloc_68_bad.yml
  c/Juliet_Test/CWE401_Memory_Leak---s01---CWE401_Memory_Leak__int_malloc_45_bad.yml
  c/Juliet_Test/CWE401_Memory_Leak---s01---CWE401_Memory_Leak__int_malloc_68_bad.yml
  c/Juliet_Test/CWE401_Memory_Leak---s01---CWE401_Memory_Leak__int_realloc_45_bad.yml
  c/Juliet_Test/CWE401_Memory_Leak---s01---CWE401_Memory_Leak__int_realloc_68_bad.yml
  c/Juliet_Test/CWE401_Memory_Leak---s03---CWE401_Memory_Leak__struct_twoIntsStruct_calloc_45_bad.yml
  c/Juliet_Test/CWE401_Memory_Leak---s03---CWE401_Memory_Leak__struct_twoIntsStruct_calloc_68_bad.yml
  c/Juliet_Test/CWE401_Memory_Leak---s03---CWE401_Memory_Leak__struct_twoIntsStruct_malloc_45_bad.yml
  c/Juliet_Test/CWE401_Memory_Leak---s03---CWE401_Memory_Leak__struct_twoIntsStruct_malloc_68_bad.yml
  c/Juliet_Test/CWE401_Memory_Leak---s03---CWE401_Memory_Leak__struct_twoIntsStruct_realloc_45_bad.yml
  c/Juliet_Test/CWE401_Memory_Leak---s03---CWE401_Memory_Leak__struct_twoIntsStruct_realloc_68_bad.yml
  c/Juliet_Test/CWE401_Memory_Leak---s03---CWE401_Memory_Leak__twoIntsStruct_calloc_45_bad.yml
  c/Juliet_Test/CWE401_Memory_Leak---s03---CWE401_Memory_Leak__twoIntsStruct_calloc_68_bad.yml
  c/Juliet_Test/CWE401_Memory_Leak---s03---CWE401_Memory_Leak__twoIntsStruct_malloc_45_bad.yml
  c/Juliet_Test/CWE401_Memory_Leak---s03---CWE401_Memory_Leak__twoIntsStruct_malloc_68_bad.yml
  c/Juliet_Test/CWE401_Memory_Leak---s03---CWE401_Memory_Leak__twoIntsStruct_realloc_45_bad.yml
  c/Juliet_Test/CWE401_Memory_Leak---s03---CWE401_Memory_Leak__twoIntsStruct_realloc_68_bad.yml
Labels: C, issue with benchmark

#1248 aws-c-common: ensure allocation of sufficient size
  c/aws-c-common/aws_byte_cursor_read_be16_harness.i
  c/aws-c-common/aws_byte_cursor_read_be32_harness.i
  c/aws-c-common/aws_byte_cursor_read_be64_harness.i
  c/aws-c-common/aws_byte_cursor_read_u8_harness.i
Labels: C, issue with benchmark

#1242 Fix verdicts for bounded divbin tasks
  c/nla-digbench-scaling/divbin_unwindbound10.yml
  c/nla-digbench-scaling/divbin_unwindbound100.yml
  c/nla-digbench-scaling/divbin_unwindbound20.yml
  c/nla-digbench-scaling/divbin_unwindbound50.yml
  c/nla-digbench-scaling/generate.py
Labels: C, issue with benchmark
