Repository sosy-lab/sv-benchmarks, pull requests merged in 2020-10, with the labels that each got.

#1144 adding tasks with nested loops.
  c/loop-simple/README.txt
  c/loop-simple/deep-nested.c
  c/loop-simple/nested_1.c
  c/loop-simple/nested_1.yml
  c/loop-simple/nested_1b.c
  c/loop-simple/nested_1b.yml
  c/loop-simple/nested_2.c
  c/loop-simple/nested_2.yml
  c/loop-simple/nested_3.c
  c/loop-simple/nested_3.yml
  c/loop-simple/nested_4.c
  c/loop-simple/nested_4.yml
  c/loop-simple/nested_5.c
  c/loop-simple/nested_5.yml
  c/loop-simple/nested_6.c
  c/loop-simple/nested_6.yml
Labels: C, new benchmarks

#1141 Adding test cases for MemSafety-Memcleanup
  c/MemSafety-MemCleanup.set
  c/memsafety/README.txt
  c/memsafety/global-atexit-1.c
  c/memsafety/global-atexit-1.i
  c/memsafety/global-atexit-1.yml
  c/memsafety/global-atexit-2.c
  c/memsafety/global-atexit-2.i
  c/memsafety/global-atexit-2a.yml
  c/memsafety/global-atexit-2b.yml
  c/memsafety/global-atexit-3.c
  c/memsafety/global-atexit-3.i
  c/memsafety/global-atexit-3.yml
  c/memsafety/global-atexit.c
  c/memsafety/global-atexit.i
  c/memsafety/global-atexit.yml
Labels: C, new benchmarks

#1161 Whitespace changes only: Re-preprocess c/openbsd-6.2
  c/openbsd-6.2/if_etherip-double-free.c
  c/openbsd-6.2/if_etherip-double-free.i
  c/openbsd-6.2/if_etherip-fixed-double-free.c
  c/openbsd-6.2/if_etherip-fixed-double-free.i
Labels: C

#1152 c/openbsd-6.2: Insert assert(0) into the body of reach_error
  c/openbsd-6.2/Makefile
  c/openbsd-6.2/if_etherip-double-free.i
  c/openbsd-6.2/if_etherip-fixed-double-free.i
  c/openbsd-6.2/sources/stubs/stub.h
  c/openbsd-6.2/sources/stubs/sv_comp.h
  c/openbsd-6.2/sources/sys/machine/cpu_full.h
Labels: C

#1167 Add some benchmark task derived from the Juliet Java benchmark publis…
  java/ReachSafety-Java.set
  java/compile.xml
  java/juliet-java/CWE369_Divide_by_Zero__float_connect_tcp_divide_01_bad.yml
  java/juliet-java/CWE369_Divide_by_Zero__float_connect_tcp_divide_01_bad/Main.java
  java/juliet-java/CWE369_Divide_by_Zero__float_connect_tcp_divide_01_bad_version2.yml
  java/juliet-java/CWE369_Divide_by_Zero__float_connect_tcp_divide_01_bad_version2/Main.java
  java/juliet-java/CWE369_Divide_by_Zero__float_connect_tcp_divide_01_good.yml
  java/juliet-java/CWE369_Divide_by_Zero__float_connect_tcp_divide_01_good/Main.java
  java/juliet-java/CWE369_Divide_by_Zero__float_connect_tcp_divide_81a_bad/CWE369_Divide_by_Zero__float_connect_tcp_divide_81_bad.java
  java/juliet-java/CWE369_Divide_by_Zero__float_connect_tcp_divide_81a_bad/CWE369_Divide_by_Zero__float_connect_tcp_divide_81_base.java
  java/juliet-java/CWE369_Divide_by_Zero__float_connect_tcp_divide_81a_bad/CWE369_Divide_by_Zero__float_connect_tcp_divide_81_goodB2G.java
  java/juliet-java/CWE369_Divide_by_Zero__float_connect_tcp_divide_81a_bad/CWE369_Divide_by_Zero__float_connect_tcp_divide_81_goodG2B.java
  java/juliet-java/CWE369_Divide_by_Zero__float_connect_tcp_divide_81a_bad/Main.java
  java/juliet-java/CWE369_Divide_by_Zero__float_connect_tcp_divide_81a_bad_version2/CWE369_Divide_by_Zero__float_connect_tcp_divide_81_bad.java
  java/juliet-java/CWE369_Divide_by_Zero__float_connect_tcp_divide_81a_bad_version2/CWE369_Divide_by_Zero__float_connect_tcp_divide_81_base.java
  java/juliet-java/CWE369_Divide_by_Zero__float_connect_tcp_divide_81a_bad_version2/CWE369_Divide_by_Zero__float_connect_tcp_divide_81_goodB2G.java
  java/juliet-java/CWE369_Divide_by_Zero__float_connect_tcp_divide_81a_bad_version2/CWE369_Divide_by_Zero__float_connect_tcp_divide_81_goodG2B.java
  java/juliet-java/CWE369_Divide_by_Zero__float_connect_tcp_divide_81a_bad_version2/Main.java
  java/juliet-java/CWE369_Divide_by_Zero__float_connect_tcp_divide_81a_good/CWE369_Divide_by_Zero__float_connect_tcp_divide_81_bad.java
  java/juliet-java/CWE369_Divide_by_Zero__float_connect_tcp_divide_81a_good/CWE369_Divide_by_Zero__float_connect_tcp_divide_81_base.java
  java/juliet-java/CWE369_Divide_by_Zero__float_connect_tcp_divide_81a_good/CWE369_Divide_by_Zero__float_connect_tcp_divide_81_goodB2G.java
  java/juliet-java/CWE369_Divide_by_Zero__float_connect_tcp_divide_81a_good/CWE369_Divide_by_Zero__float_connect_tcp_divide_81_goodG2B.java
  java/juliet-java/CWE369_Divide_by_Zero__float_connect_tcp_divide_81a_good/Main.java
  java/juliet-java/CWE369_Divide_by_Zero__float_console_readLine_divide_54_bad/CWE369_Divide_by_Zero__float_console_readLine_divide_54b.java
  java/juliet-java/CWE369_Divide_by_Zero__float_console_readLine_divide_54_bad/CWE369_Divide_by_Zero__float_console_readLine_divide_54c.java
  java/juliet-java/CWE369_Divide_by_Zero__float_console_readLine_divide_54_bad/CWE369_Divide_by_Zero__float_console_readLine_divide_54d.java
  java/juliet-java/CWE369_Divide_by_Zero__float_console_readLine_divide_54_bad/CWE369_Divide_by_Zero__float_console_readLine_divide_54e.java
  java/juliet-java/CWE369_Divide_by_Zero__float_console_readLine_divide_54_bad/Main.java
  java/juliet-java/CWE369_Divide_by_Zero__float_console_readLine_divide_54_bad_version2/CWE369_Divide_by_Zero__float_console_readLine_divide_54b.java
  java/juliet-java/CWE369_Divide_by_Zero__float_console_readLine_divide_54_bad_version2/CWE369_Divide_by_Zero__float_console_readLine_divide_54c.java
  java/juliet-java/CWE369_Divide_by_Zero__float_console_readLine_divide_54_bad_version2/CWE369_Divide_by_Zero__float_console_readLine_divide_54d.java
  java/juliet-java/CWE369_Divide_by_Zero__float_console_readLine_divide_54_bad_version2/CWE369_Divide_by_Zero__float_console_readLine_divide_54e.java
  java/juliet-java/CWE369_Divide_by_Zero__float_console_readLine_divide_54_bad_version2/Main.java
  java/juliet-java/CWE369_Divide_by_Zero__float_console_readLine_divide_54_good/CWE369_Divide_by_Zero__float_console_readLine_divide_54b.java
  java/juliet-java/CWE369_Divide_by_Zero__float_console_readLine_divide_54_good/CWE369_Divide_by_Zero__float_console_readLine_divide_54c.java
  java/juliet-java/CWE369_Divide_by_Zero__float_console_readLine_divide_54_good/CWE369_Divide_by_Zero__float_console_readLine_divide_54d.java
  java/juliet-java/CWE369_Divide_by_Zero__float_console_readLine_divide_54_good/CWE369_Divide_by_Zero__float_console_readLine_divide_54e.java
  java/juliet-java/CWE369_Divide_by_Zero__float_console_readLine_divide_54_good/Main.java
  java/juliet-java/CWE369_Divided_by_Zero__float_connect_tcp_divide_81a_bad.yml
  java/juliet-java/CWE369_Divided_by_Zero__float_connect_tcp_divide_81a_bad_version2.yml
  java/juliet-java/CWE369_Divided_by_Zero__float_connect_tcp_divide_81a_good.yml
  java/juliet-java/CWE369_Divided_by_Zero__float_console_readLine_divide_54_bad.yml
  java/juliet-java/CWE369_Divided_by_Zero__float_console_readLine_divide_54_bad_version2.yml
  java/juliet-java/CWE369_Divided_by_Zero__float_console_readLine_divide_54_good.yml
  java/juliet-java/License-CC0.txt
  java/juliet-java/README.md
  java/juliet-java/testcasesupport/testcasesupport/BufferedReader.java
  java/juliet-java/testcasesupport/testcasesupport/IO.java
Labels: Java, new benchmarks

#1011 [JAVA] Adding a 2nd property on the replace benchmark
  java/ReachSafety-Java.set
  java/java-ranger-regression/replace5_eqchk/Main.java
  java/java-ranger-regression/replace5_eqchk/TestVeritestingReplace.java
  java/java-ranger-regression/replace5_eqchk/impl/Outputs.java
  java/java-ranger-regression/replace5_eqchk/impl/Replace.java
  java/java-ranger-regression/replace5_eqchk/prop1/Main.java
  java/java-ranger-regression/replace5_eqchk/prop2/Main.java
  java/java-ranger-regression/replace5_eqchk/replace.java
  java/java-ranger-regression/replace5_eqchk/replace5_prop1.yml
  java/java-ranger-regression/replace5_eqchk/replace5_prop2.yml
Labels: Java, category definitions

#1008 [Java] Adding a 2nd property on NanoXML
  java/ReachSafety-Java.set
  java/java-ranger-regression/nanoxml_eqchk/Main.java
  java/java-ranger-regression/nanoxml_eqchk/TestVeritestingDumpXML.java
  java/java-ranger-regression/nanoxml_eqchk/impl/ContentReader.java
  java/java-ranger-regression/nanoxml_eqchk/impl/DumpXML.java
  java/java-ranger-regression/nanoxml_eqchk/impl/IXMLBuilder.java
  java/java-ranger-regression/nanoxml_eqchk/impl/IXMLParser.java
  java/java-ranger-regression/nanoxml_eqchk/impl/IXMLReader.java
  java/java-ranger-regression/nanoxml_eqchk/impl/IXMLValidator.java
  java/java-ranger-regression/nanoxml_eqchk/impl/IntReader.java
  java/java-ranger-regression/nanoxml_eqchk/impl/NonValidator.java
  java/java-ranger-regression/nanoxml_eqchk/impl/StdXMLBuilder.java
  java/java-ranger-regression/nanoxml_eqchk/impl/StdXMLParser.java
  java/java-ranger-regression/nanoxml_eqchk/impl/StdXMLReader.java
  java/java-ranger-regression/nanoxml_eqchk/impl/XMLElement.java
  java/java-ranger-regression/nanoxml_eqchk/impl/XMLParseException.java
  java/java-ranger-regression/nanoxml_eqchk/impl/XMLParserFactory.java
  java/java-ranger-regression/nanoxml_eqchk/impl/XMLValidationException.java
  java/java-ranger-regression/nanoxml_eqchk/impl/XMLWriter.java
  java/java-ranger-regression/nanoxml_eqchk/nanoxml_prop1.yml
  java/java-ranger-regression/nanoxml_eqchk/nanoxml_prop2.yml
  java/java-ranger-regression/nanoxml_eqchk/nanoxml_prop3.yml
  java/java-ranger-regression/nanoxml_eqchk/prop1/Main.java
  java/java-ranger-regression/nanoxml_eqchk/prop2/Main.java
  java/java-ranger-regression/nanoxml_eqchk/prop3/Main.java
Labels: Java, category definitions

#1169 Add the Jdart regression test to SV-COMP
  java/ReachSafety-Java.set
  java/compile.xml
  java/jdart-regression/LICENSE-4-clause-BSD.txt
  java/jdart-regression/LICENSE-Apache
  java/jdart-regression/LICENSE-MIT
  java/jdart-regression/OverapproximationString01.yml
  java/jdart-regression/OverapproximationString01/Main.java
  java/jdart-regression/URLDecoder01.yml
  java/jdart-regression/URLDecoder01/Main.java
  java/jdart-regression/URLDecoder02.yml
  java/jdart-regression/URLDecoder02/Main.java
  java/jdart-regression/addition01.yml
  java/jdart-regression/addition01/Main.java
  java/jdart-regression/array-iteration01.yml
  java/jdart-regression/array-iteration01/Main.java
  java/jdart-regression/boundcheck100.yml
  java/jdart-regression/boundcheck100/Main.java
  java/jdart-regression/boundcheck200.yml
  java/jdart-regression/boundcheck200/Main.java
  java/jdart-regression/boundcheck30.yml
  java/jdart-regression/boundcheck30/Main.java
  java/jdart-regression/double2long.yml
  java/jdart-regression/double2long/Main.java
  java/jdart-regression/float.yml
  java/jdart-regression/float/Main.java
  java/jdart-regression/list2.yml
  java/jdart-regression/list2/Main.java
  java/jdart-regression/radians.yml
  java/jdart-regression/radians/Main.java
  java/jdart-regression/shifting.yml
  java/jdart-regression/shifting/Main.java
  java/jdart-regression/shifting2.yml
  java/jdart-regression/shifting2/Main.java
  java/jdart-regression/shifting3.yml
  java/jdart-regression/shifting3/Main.java
  java/jdart-regression/startswith.yml
  java/jdart-regression/startswith/Main.java
Labels: Java, new benchmarks

#1140 change MemSafety sub-categories #841
  c/MemSafety-Arrays.set
  c/MemSafety-Other.set
  c/MemSafety-TerminCrafted.set
Labels: C, category definitions

#1009 [JAVA] Adding a 2nd property to check on PrintTokens2
  java/ReachSafety-Java.set
  java/java-ranger-regression/printtokens_eqchk/IntReader.java
  java/java-ranger-regression/printtokens_eqchk/Main.java
  java/java-ranger-regression/printtokens_eqchk/TestPrintTokens.java
  java/java-ranger-regression/printtokens_eqchk/impl/IntReader.java
  java/java-ranger-regression/printtokens_eqchk/impl/PrintTokens2.java
  java/java-ranger-regression/printtokens_eqchk/impl/TokenStream.java
  java/java-ranger-regression/printtokens_eqchk/printTokens2.java
  java/java-ranger-regression/printtokens_eqchk/printtokens_prop1.yml
  java/java-ranger-regression/printtokens_eqchk/printtokens_prop2.yml
  java/java-ranger-regression/printtokens_eqchk/prop1/Main.java
  java/java-ranger-regression/printtokens_eqchk/prop2/Main.java
Labels: Java, category definitions

#1179 Port undefined behavior fixes from #1164 to goblint-regression races-as-reachability benchmarks
  c/goblint-regression/28-race_reach_23-sound_unlock_racing.c
  c/goblint-regression/28-race_reach_23-sound_unlock_racing.i
  c/goblint-regression/28-race_reach_36-indirect_racefree.c
  c/goblint-regression/28-race_reach_36-indirect_racefree.i
  c/goblint-regression/28-race_reach_37-indirect_racing.c
  c/goblint-regression/28-race_reach_37-indirect_racing.i
  c/goblint-regression/28-race_reach_40-trylock_racing.c
  c/goblint-regression/28-race_reach_40-trylock_racing.i
  c/goblint-regression/28-race_reach_70-funloop_racefree.c
  c/goblint-regression/28-race_reach_70-funloop_racefree.i
  c/goblint-regression/28-race_reach_71-funloop_racing.c
  c/goblint-regression/28-race_reach_71-funloop_racing.i
  c/goblint-regression/28-race_reach_72-funloop_hard_racing.c
  c/goblint-regression/28-race_reach_72-funloop_hard_racing.i
  c/goblint-regression/28-race_reach_73-funloop_hard_racefree.c
  c/goblint-regression/28-race_reach_73-funloop_hard_racefree.i
  c/goblint-regression/28-race_reach_74-tricky_address1_racefree.c
  c/goblint-regression/28-race_reach_74-tricky_address1_racefree.i
  c/goblint-regression/28-race_reach_75-tricky_address2_racefree.c
  c/goblint-regression/28-race_reach_75-tricky_address2_racefree.i
  c/goblint-regression/28-race_reach_76-tricky_address3_racefree.c
  c/goblint-regression/28-race_reach_76-tricky_address3_racefree.i
  c/goblint-regression/28-race_reach_77-tricky_address4_racing.c
  c/goblint-regression/28-race_reach_77-tricky_address4_racing.i
  c/goblint-regression/28-race_reach_78-equ_racing.c
  c/goblint-regression/28-race_reach_78-equ_racing.i
  c/goblint-regression/28-race_reach_79-equ_racefree.c
  c/goblint-regression/28-race_reach_79-equ_racefree.i
Labels: C, data-race, issue with benchmark

#1186 Fixes for Integer Overflows
  c/array-cav19/array_tiling_poly6.c
  c/array-cav19/array_tiling_tcpy.c
Labels: C, issue with benchmark

#1182 Fix undefined behaviors in AWS
  c/aws-c-common/aws_array_eq_c_str_harness.i
  c/aws-c-common/aws_array_eq_c_str_ignore_case_harness.i
  c/aws-c-common/aws_array_eq_harness.i
  c/aws-c-common/aws_array_eq_ignore_case_harness.i
  c/aws-c-common/aws_array_list_back_harness.i
  c/aws-c-common/aws_array_list_capacity_harness.i
  c/aws-c-common/aws_array_list_clean_up_harness.i
  c/aws-c-common/aws_array_list_clear_harness.i
  c/aws-c-common/aws_array_list_comparator_string_harness.i
  c/aws-c-common/aws_array_list_ensure_capacity_harness.i
  c/aws-c-common/aws_array_list_erase_harness.i
  c/aws-c-common/aws_array_list_front_harness.i
  c/aws-c-common/aws_array_list_get_at_harness.i
  c/aws-c-common/aws_array_list_get_at_ptr_harness.i
  c/aws-c-common/aws_array_list_init_dynamic_harness.i
  c/aws-c-common/aws_array_list_init_static_harness.i
  c/aws-c-common/aws_array_list_length_harness.i
  c/aws-c-common/aws_array_list_pop_back_harness.i
  c/aws-c-common/aws_array_list_pop_front_harness.i
  c/aws-c-common/aws_array_list_pop_front_n_harness.i
  c/aws-c-common/aws_array_list_push_back_harness.i
  c/aws-c-common/aws_array_list_set_at_harness.i
  c/aws-c-common/aws_array_list_shrink_to_fit_harness.i
  c/aws-c-common/aws_array_list_sort_harness.i
  c/aws-c-common/aws_array_list_swap_harness.i
  c/aws-c-common/aws_byte_buf_advance_harness.i
  c/aws-c-common/aws_byte_buf_cat_harness.i
  c/aws-c-common/aws_byte_buf_eq_c_str_harness.i
  c/aws-c-common/aws_byte_buf_eq_c_str_ignore_case_harness.i
  c/aws-c-common/aws_byte_buf_write_from_whole_string_harness.i
  c/aws-c-common/aws_byte_buf_write_harness.i
  c/aws-c-common/aws_byte_cursor_advance_harness.i
  c/aws-c-common/aws_byte_cursor_advance_nospec_harness.i
  c/aws-c-common/aws_byte_cursor_from_buf_harness.i
  c/aws-c-common/aws_byte_cursor_read_and_fill_buffer_harness.i
  c/aws-c-common/aws_byte_cursor_read_be16_harness.i
  c/aws-c-common/aws_byte_cursor_read_be32_harness.i
  c/aws-c-common/aws_byte_cursor_read_be64_harness.i
  c/aws-c-common/aws_byte_cursor_read_harness.i
  c/aws-c-common/aws_byte_cursor_read_u8_harness.i
  c/aws-c-common/aws_hash_iter_delete_harness.i
  c/aws-c-common/aws_hash_iter_done_harness.i
  c/aws-c-common/aws_hash_iter_next_harness.i
  c/aws-c-common/aws_is_power_of_two_harness.i
  c/aws-c-common/aws_nospec_mask_harness.i
  c/aws-c-common/aws_round_up_to_power_of_two_harness.i
  c/aws-c-common/aws_string_eq_byte_buf_harness.i
  c/aws-c-common/aws_string_eq_byte_cursor_harness.i
Labels: C, issue with benchmark

#1187 Cleaned up definitions of memcmp function
  c/aws-c-common/aws_array_eq_c_str_harness.i
  c/aws-c-common/aws_array_eq_c_str_ignore_case_harness.i
  c/aws-c-common/aws_array_eq_harness.i
  c/aws-c-common/aws_array_eq_ignore_case_harness.i
  c/aws-c-common/aws_byte_buf_cat_harness.i
  c/aws-c-common/aws_byte_buf_eq_c_str_harness.i
  c/aws-c-common/aws_byte_buf_eq_c_str_ignore_case_harness.i
  c/aws-c-common/aws_byte_buf_eq_harness.i
  c/aws-c-common/aws_byte_buf_eq_ignore_case_harness.i
  c/aws-c-common/aws_byte_cursor_compare_lexical_harness.i
  c/aws-c-common/aws_byte_cursor_compare_lookup_harness.i
  c/aws-c-common/aws_byte_cursor_eq_byte_buf_harness.i
  c/aws-c-common/aws_byte_cursor_eq_byte_buf_ignore_case_harness.i
  c/aws-c-common/aws_byte_cursor_eq_c_str_harness.i
  c/aws-c-common/aws_byte_cursor_eq_c_str_ignore_case_harness.i
  c/aws-c-common/aws_byte_cursor_eq_harness.i
  c/aws-c-common/aws_byte_cursor_eq_ignore_case_harness.i
  c/aws-c-common/aws_hash_callback_c_str_eq_harness.i
  c/aws-c-common/aws_hash_callback_string_eq_harness.i
Labels: C, issue with benchmark

#1178 Remove duplicated benchmarks
  c/pthread-ext/15_dekker-b.c
  c/pthread-ext/15_dekker-b.i
  c/pthread-ext/15_dekker-b.yml
  c/pthread-ext/15_dekker.c
  c/pthread-ext/15_dekker.i
  c/pthread-ext/15_dekker.yml
  c/pthread-ext/16_peterson-b.c
  c/pthread-ext/16_peterson-b.i
  c/pthread-ext/16_peterson-b.yml
  c/pthread-ext/16_peterson.c
  c/pthread-ext/16_peterson.i
  c/pthread-ext/16_peterson.yml
  c/pthread-ext/19_time_var_mutex.c
  c/pthread-ext/19_time_var_mutex.i
  c/pthread-ext/19_time_var_mutex.yml
  c/pthread-ext/20_lamport-b.c
  c/pthread-ext/20_lamport-b.i
  c/pthread-ext/20_lamport-b.yml
  c/pthread-ext/20_lamport.c
  c/pthread-ext/20_lamport.i
  c/pthread-ext/20_lamport.yml
Labels: C

#1177 Solved Data-Races
  c/ldv-races/race-2_5-container_of.c
  c/ldv-races/race-2_5-container_of.i
  c/ldv-races/race-3_2-container_of-global.c
  c/ldv-races/race-3_2-container_of-global.i
  c/pthread-atomic/dekker.c
  c/pthread-atomic/dekker.i
  c/pthread-atomic/lamport.c
  c/pthread-atomic/lamport.i
  c/pthread-atomic/peterson.c
  c/pthread-atomic/peterson.i
  c/pthread-atomic/read_write_lock-1.c
  c/pthread-atomic/read_write_lock-1.i
  c/pthread-atomic/read_write_lock-2.c
  c/pthread-atomic/read_write_lock-2.i
  c/pthread-atomic/szymanski.c
  c/pthread-atomic/szymanski.i
  c/pthread-ext/01_inc-b.c
  c/pthread-ext/01_inc-b.i
  c/pthread-ext/01_inc-b.yml
  c/pthread-ext/02_inc_cas.c
  c/pthread-ext/02_inc_cas.i
  c/pthread-ext/39_rand_lock_p0_vs.c
  c/pthread-ext/39_rand_lock_p0_vs.i
  c/pthread-ext/40_barrier_vf.c
  c/pthread-ext/40_barrier_vf.i
  c/pthread-lit/qw2004-2.c
  c/pthread-lit/qw2004-2.i
Labels: C, data-race, issue with benchmark

#1193 Shrink Juliet MemSafety integration
  c/MemSafety-Juliet.set
  c/Unused_Juliet.set
Labels: C, category definitions

#1194 Re-add more juliet tasks
  c/MemSafety-Juliet.set
Labels: C, category definitions
